# Generated by Django 5.0.7 on 2024-10-07 14:27

import django.db.models.deletion
import iaweb.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HealthCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Health Center Name"),
                ),
                (
                    "city",
                    models.CharField(max_length=100, verbose_name="Health Center City"),
                ),
                (
                    "country",
                    models.CharField(
                        max_length=100, verbose_name="Health Center Country"
                    ),
                ),
                ("date_published", models.DateTimeField(verbose_name="Date Published")),
            ],
            options={
                "verbose_name": "Health Center",
                "verbose_name_plural": "Health Centers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Patient Name")),
                ("age", models.IntegerField(verbose_name="Patient Age")),
                (
                    "sex",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        max_length=10,
                        verbose_name="Sex",
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(blank=True, null=True, verbose_name="Symptoms"),
                ),
                (
                    "observations",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observations"
                    ),
                ),
                ("date_published", models.DateTimeField(verbose_name="Date Published")),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[("Blood", "Blood"), ("Urine", "Urine")], max_length=5
                    ),
                ),
                ("date_published", models.DateTimeField(verbose_name="Date Published")),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Available"),
                ),
                (
                    "health_center",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="health_center",
                        to="iaweb.healthcenter",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient",
                        to="iaweb.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sample",
                "verbose_name_plural": "Samples",
                "ordering": ["-date_published"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_published", models.DateTimeField(verbose_name="Date Published")),
                (
                    "number_of_images",
                    models.IntegerField(default=0, verbose_name="Number of Images"),
                ),
                (
                    "total_time",
                    models.IntegerField(default=0, verbose_name="Total Time (minutes)"),
                ),
                (
                    "parasites_count",
                    models.IntegerField(default=0, verbose_name="Parasites Count"),
                ),
                (
                    "leucocytes_count",
                    models.IntegerField(default=0, verbose_name="Leucocytes Count"),
                ),
                (
                    "parasitemia_level",
                    models.IntegerField(default=0, verbose_name="Parasitemia Level"),
                ),
                (
                    "diagnosis_result",
                    models.BooleanField(default=False, verbose_name="Diagnosis Result"),
                ),
                (
                    "diseases",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Diseases",
                        to="iaweb.disease",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Sample",
                        to="iaweb.sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Diagnosis Report",
                "verbose_name_plural": "Diagnosis Reports",
                "ordering": ["-date_published"],
            },
        ),
        migrations.CreateModel(
            name="SampleImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=iaweb.models.SampleImage.sample_image_upload_to
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date Published"
                    ),
                ),
                ("detection_results", models.JSONField(blank=True, null=True)),
                (
                    "detected_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=iaweb.models.SampleImage.sample_image_upload_to_detection,
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="iaweb.sample",
                        verbose_name="Sample",
                    ),
                ),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
                "ordering": ["-date_published"],
            },
        ),
    ]
